apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: engines.qixmanager.qlik.com
spec:
  group: qixmanager.qlik.com
  names:
    kind: Engine
    listKind: EngineList
    plural: engines
    singular: engine
    shortNames:
      - en
  scope: Namespaced
  version: v1
