{{- if or .Values.global.mongodb.uri .Values.devMode.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongoconfig
type: Opaque
data:
  {{ if .Values.mongodb.uri -}}
  mongodb-uri: {{ .Values.global.mongodb.uri | b64enc }}
  {{ else -}}
  mongodb-uri: {{ print "mongodb://" .Release.Name "-mongodb:27017/qsefe?ssl=false" | b64enc }}
  {{ end -}}
{{- end}}
